// Trade-health value strings are generated by the Rust backend in English (they also feed
// Discord notifications, which stay English by design). For UI display we translate them via a
// closed English→key map; any unmapped/dynamic string falls back to the original English text.
import type { TranslateFn } from '../i18n';
import type { TranslationKey } from '../i18n/en';

const HEALTH_LABEL_KEYS: Record<string, TranslationKey> = {
  'Action Needed': 'health.actionNeeded',
  'At market': 'health.atMarket',
  Balanced: 'health.balanced',
  Building: 'health.building',
  Competitive: 'health.competitive',
  'Competitive, but may take time': 'health.competitiveSlow',
  'Do not chase down': 'health.dontChase',
  Falling: 'health.falling',
  Flat: 'health.flat',
  Healthy: 'health.healthy',
  'Likely soon': 'health.likelySoon',
  'Low priority listing': 'health.lowPriority',
  'Needs a refresh': 'health.needsRefresh',
  'Reprice to market': 'health.reprice',
  Rising: 'health.rising',
  'Slightly above': 'health.slightlyAbove',
  'Thin market': 'health.thinMarket',
  'Wait for normalization': 'health.waitNormalize',
  Hold: 'health.hold',
  'Trim by 1-2p': 'health.trim',
  'Unlikely at current price': 'health.unlikely',
  'Needs patience': 'health.needsPatience',
  Strong: 'health.strong',
  Watch: 'health.watch',
  Weak: 'health.weak',
  Leading: 'health.leading',
  Buried: 'health.buried',
};

/** Translate a backend health-value string, falling back to the raw English if unmapped. */
export function tHealth(t: TranslateFn, value: string | null | undefined): string {
  if (!value) {
    return '';
  }
  const key = HEALTH_LABEL_KEYS[value];
  return key ? t(key) : value;
}
